# Copyright (c) 2025 MariaDB
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301
# USA

########################################################################

use strict;

unless ($ENV{WORKSPACE}) {
  $ENV{WORKSPACE}='/tmp/'.time();
}

# innodb-buffer-pool-size is scaled down
$combinations = [
  ['
    --seed=time
    --reporters=Backtrace,Deadlock
    --grammar=conf/yy/alter_table_safe.yy
    --gendata=conf/zz/blobs.zz
    --gendata=conf/zz/current_timestamp.zz
    --gendata=conf/zz/custom.zz
    --gendata=conf/zz/full_text_search.zz
    --gendata=conf/zz/oltp-aria.zz
    --gendata=conf/zz/oltp.zz
    --gendata=conf/zz/optimizer_basic.zz
    --gendata=conf/zz/temporal.zz
    --gendata=data/dbt3/dbt3-s0.0001.dump
    --gendata=data/sql/updateable_views.sql
    --gendata=advanced
    --views=MERGE,TEMPTABLE
    --vcols
    --partitions
    --reporters=Backtrace,Deadlock,FeatureUsage
  '],
  ['
      --server1-basedir=$ENV{WORKSPACE}/10.6.18-14
      --scenario=NormalUpgrades
      --threads=1
      --duration=60
      --queries=10
      --mysqld=--binlog_annotate_row_events=OFF
      --mysqld=--binlog_cache_size=1048576
      --mysqld=--binlog_expire_logs_seconds=432000
      --mysqld=--binlog_format=ROW
      --mysqld=--binlog_stmt_cache_size=131072
      --mysqld=--character_set_server=utf8mb3
      --mysqld=--collation_server=utf8mb3_general_ci
      --mysqld=--default_password_lifetime=90
      --mysqld=--disconnect_on_expired_password=ON
      --mysqld=--expire_logs_days=5.0
      --mysqld=--explicit_defaults_for_timestamp=ON
      --mysqld=--gtid_strict_mode=ON
      --mysqld=--host_cache_size=1103
      --mysqld=--ignore_db_dirs=lost+found
      --mysqld=--innodb_autoinc_lock_mode=2
      --mysqld=--innodb_buffer_pool_size=4G
      --mysqld=--innodb_flush_neighbors=0
      --mysqld=--innodb_io_capacity=400
      --mysqld=--innodb_io_capacity_max=4000
      --mysqld=--innodb_lock_wait_timeout=180
      --mysqld=--innodb_log_buffer_size=67108864
      --mysqld=--innodb_log_file_size=4294967296
      --mysqld=--innodb_max_dirty_pages_pct=50.0
      --mysqld=--innodb_open_files=2048
      --mysqld=--innodb_print_all_deadlocks=ON
      --mysqld=--innodb_read_io_threads=8
      --mysqld=--innodb_sort_buffer_size=12582912
      --mysqld=--innodb_write_io_threads=8
      --mysqld=--join_buffer_size=4194304
      --mysqld=--join_buffer_space_limit=4194304
      --mysqld=--join_cache_level=6
      --mysqld=--key_buffer_size=67108864
      --mysqld=--lock_wait_timeout=10800
      --mysqld=--log_bin
      --mysqld=--log_bin_compress=ON
      --mysqld=--log_bin_trust_function_creators=ON
      --mysqld=--log_slave_updates=ON
      --mysqld=--log_slow_verbosity=innodb,query_plan
      --mysqld=--long_query_time=30
      --mysqld=--lower_case_table_names=1
      --mysqld=--master_verify_checksum=ON
      --mysqld=--max_allowed_packet=67108864
      --mysqld=--max_binlog_size=268435456
      --mysqld=--max_connect_errors=10000
      --mysqld=--max_connections=10000
      --mysqld=--max_heap_table_size=33554432
      --mysqld=--max_password_errors=5
      --mysqld=--max_relay_log_size=268435456
      --mysqld=--myisam_recover_options=BACKUP,FORCE
      --mysqld=--myisam_sort_buffer_size=67108864
      --mysqld=--open_files_limit=278528
      --mysqld=--optimizer_search_depth=0
      --mysqld=--optimizer_switch=index_merge=on,index_merge_union=on,index_merge_sort_union=on,index_merge_intersection=on,index_merge_sort_intersection=off,engine_condition_pushdown=off,index_condition_pushdown=on,derived_merge=on,derived_with_keys=on,firstmatch=on,loosescan=on,materialization=on,in_to_exists=on,semijoin=on,partial_match_rowid_merge=on,partial_match_table_scan=on,subquery_cache=on,mrr=on,mrr_cost_based=on,mrr_sort_keys=off,outer_join_with_cache=on,semijoin_with_cache=on,join_cache_incremental=on,join_cache_hashed=on,join_cache_bka=on,optimize_join_buffer_size=on,table_elimination=on,extended_keys=on,exists_to_in=on,orderby_uses_equalities=on,condition_pushdown_for_derived=on,split_materialized=on,condition_pushdown_for_subquery=on,rowid_filter=on,condition_pushdown_from_having=on,not_null_range_scan=off,hash_join_cardinality=off,cset_narrowing=off,sargable_casefold=off
      --mysqld=--plugin_maturity=stable
      --mysqld=--proxy_protocol_networks=*
      --mysqld=--query_cache_size=0
      --mysqld=--relay_log_recovery=ON
      --mysqld=--replicate_events_marked_for_skip=FILTER_ON_MASTER
      --mysqld=--rpl_semi_sync_master_enabled=ON
      --mysqld=--rpl_semi_sync_slave_enabled=ON
      --mysqld=--server_audit_file_rotate_now=OFF
      --mysqld=--server_audit_file_rotate_size=50000000
      --mysqld=--server_audit_file_rotations=100
      --mysqld=--server_audit_load_on_error=ON
      --mysqld=--server_audit_logging=ON
      --mysqld=--server_audit_mode=0
      --mysqld=--server_audit_output_type=file
      --mysqld=--server_audit_query_log_limit=1024
      --mysqld=--server_audit_reload_filters=OFF
      --mysqld=--server_audit_syslog_facility=LOG_USER
      --mysqld=--server_audit_syslog_ident=mysql-server_auditing
      --mysqld=--server_audit_syslog_info=
      --mysqld=--server_audit_syslog_priority=LOG_INFO
      --mysqld=--server_audit_timestamp_format=%Y%m%d %H:%i:%s
      --mysqld=--shutdown_wait_for_slaves=ON
      --mysqld=--simple_password_check_digits=1
      --mysqld=--simple_password_check_letters_same_case=1
      --mysqld=--simple_password_check_minimal_length=15
      --mysqld=--simple_password_check_other_characters=1
      --mysqld=--slave_net_timeout=10
      --mysqld=--slave_parallel_max_queued=67108864
      --mysqld=--slave_parallel_threads=4
      --mysqld=--slave_parallel_workers=4
      --mysqld=--slow_query_log=ON
      --mysqld=--sql_error_log_rate=1
      --mysqld=--sql_error_log_rotate=OFF
      --mysqld=--sql_error_log_rotations=9
      --mysqld=--sql_error_log_size_limit=268435456
      --mysqld=--sql_error_log_with_db_and_thread_info=OFF
      --mysqld=--sql_mode=PIPES_AS_CONCAT,ANSI_QUOTES,IGNORE_SPACE,ORACLE,NO_KEY_OPTIONS,NO_TABLE_OPTIONS,NO_FIELD_OPTIONS,STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,SIMULTANEOUS_ASSIGNMENT
      --mysqld=--sync_binlog=1
      --mysqld=--sync_master_info=1
      --mysqld=--table_definition_cache=16384
      --mysqld=--table_open_cache=16384
      --mysqld=--thread_cache_size=256
      --mysqld=--thread_pool_size=16
      --mysqld=--thread_stack=262144
      --mysqld=--tmp_memory_table_size=33554432
      --mysqld=--tmp_table_size=33554432
      --mysqld=--transaction_isolation=READ-COMMITTED
      --mysqld=--use_stat_tables=PREFERABLY
      --mysqld=--userstat=ON
      --mysqld=--wait_timeout=3600
      --mysqld=--plugin-load-add=server_audit2
      --mysqld=--plugin-load-add=simple_password_check
      --mysqld=--plugin-load-add=sql_errlog
      --mysqld=--innodb_log_group_home_dir=$ENV{WORKSPACE}/1-1/mariadb/data
      --mysqld=--log_bin_basename=$ENV{WORKSPACE}/1-1/mariadb/bin/logs/bin_logs/bin_log
      --mysqld=--log_bin_index=$ENV{WORKSPACE}/1-1/mariadb/bin/logs/bin_logs/master_bin_log.index
      --mysqld=--log_error=$ENV{WORKSPACE}/1-1/mariadb/bin/logs/db_logs/error_mariadb.log
      --mysqld=--server_audit_file_path=$ENV{WORKSPACE}/1-1/mariadb/bin/logs/audit_logs/audit_mariadb.log
      --mysqld=--slave_load_tmpdir=$ENV{WORKSPACE}/1-1/mariadb/tmp
      --mysqld=--slow_query_log_file=$ENV{WORKSPACE}/1-1/mariadb/bin/logs/db_logs/slow_query_mariadb.log
      --mysqld=--sql_error_log_filename=$ENV{WORKSPACE}/1-1/mariadb/bin/logs/db_logs/sql_error_mariadb.log
      --mysqld=--tmpdir=$ENV{WORKSPACE}/1-1/mariadb/tmp
      --mysqld=--wsrep_data_home_dir=$ENV{WORKSPACE}/1-1/mariadb/data/
  '],
  ['
      --server1-basedir=$ENV{WORKSPACE}/10.6.18-14
      --scenario=Replication
      --duration=300
      --threads=4
      --mysqld=--binlog_annotate_row_events=OFF
      --mysqld=--binlog_cache_size=1048576
      --mysqld=--binlog_expire_logs_seconds=432000
      --mysqld=--binlog_format=ROW
      --mysqld=--binlog_stmt_cache_size=131072
      --mysqld=--character_set_server=utf8mb3
      --mysqld=--collation_server=utf8mb3_general_ci
      --mysqld=--default_password_lifetime=90
      --mysqld=--disconnect_on_expired_password=ON
      --mysqld=--expire_logs_days=5.0
      --mysqld=--explicit_defaults_for_timestamp=ON
      --mysqld=--gtid_strict_mode=ON
      --mysqld=--host_cache_size=1103
      --mysqld=--ignore_db_dirs=lost+found
      --mysqld=--innodb_autoinc_lock_mode=2
      --mysqld=--innodb_buffer_pool_size=4G
      --mysqld=--innodb_flush_neighbors=0
      --mysqld=--innodb_io_capacity=400
      --mysqld=--innodb_io_capacity_max=4000
      --mysqld=--innodb_lock_wait_timeout=180
      --mysqld=--innodb_log_buffer_size=67108864
      --mysqld=--innodb_log_file_size=4294967296
      --mysqld=--innodb_max_dirty_pages_pct=50.0
      --mysqld=--innodb_open_files=2048
      --mysqld=--innodb_print_all_deadlocks=ON
      --mysqld=--innodb_read_io_threads=8
      --mysqld=--innodb_sort_buffer_size=12582912
      --mysqld=--innodb_write_io_threads=8
      --mysqld=--join_buffer_size=4194304
      --mysqld=--join_buffer_space_limit=4194304
      --mysqld=--join_cache_level=6
      --mysqld=--key_buffer_size=67108864
      --mysqld=--lock_wait_timeout=10800
      --mysqld=--log_bin
      --mysqld=--log_bin_compress=ON
      --mysqld=--log_bin_trust_function_creators=ON
      --mysqld=--log_slave_updates=ON
      --mysqld=--log_slow_verbosity=innodb,query_plan
      --mysqld=--long_query_time=30
      --mysqld=--lower_case_table_names=1
      --mysqld=--master_verify_checksum=ON
      --mysqld=--max_allowed_packet=67108864
      --mysqld=--max_binlog_size=268435456
      --mysqld=--max_connect_errors=10000
      --mysqld=--max_connections=10000
      --mysqld=--max_heap_table_size=33554432
      --mysqld=--max_password_errors=5
      --mysqld=--max_relay_log_size=268435456
      --mysqld=--myisam_recover_options=BACKUP,FORCE
      --mysqld=--myisam_sort_buffer_size=67108864
      --mysqld=--open_files_limit=278528
      --mysqld=--optimizer_search_depth=0
      --mysqld=--optimizer_switch=index_merge=on,index_merge_union=on,index_merge_sort_union=on,index_merge_intersection=on,index_merge_sort_intersection=off,engine_condition_pushdown=off,index_condition_pushdown=on,derived_merge=on,derived_with_keys=on,firstmatch=on,loosescan=on,materialization=on,in_to_exists=on,semijoin=on,partial_match_rowid_merge=on,partial_match_table_scan=on,subquery_cache=on,mrr=on,mrr_cost_based=on,mrr_sort_keys=off,outer_join_with_cache=on,semijoin_with_cache=on,join_cache_incremental=on,join_cache_hashed=on,join_cache_bka=on,optimize_join_buffer_size=on,table_elimination=on,extended_keys=on,exists_to_in=on,orderby_uses_equalities=on,condition_pushdown_for_derived=on,split_materialized=on,condition_pushdown_for_subquery=on,rowid_filter=on,condition_pushdown_from_having=on,not_null_range_scan=off,hash_join_cardinality=off,cset_narrowing=off,sargable_casefold=off
      --mysqld=--plugin_maturity=stable
      --mysqld=--proxy_protocol_networks=*
      --mysqld=--query_cache_size=0
      --mysqld=--relay_log_recovery=ON
      --mysqld=--replicate_events_marked_for_skip=FILTER_ON_MASTER
      --mysqld=--rpl_semi_sync_master_enabled=ON
      --mysqld=--rpl_semi_sync_slave_enabled=ON
      --mysqld=--server_audit_file_rotate_now=OFF
      --mysqld=--server_audit_file_rotate_size=50000000
      --mysqld=--server_audit_file_rotations=100
      --mysqld=--server_audit_load_on_error=ON
      --mysqld=--server_audit_logging=ON
      --mysqld=--server_audit_mode=0
      --mysqld=--server_audit_output_type=file
      --mysqld=--server_audit_query_log_limit=1024
      --mysqld=--server_audit_reload_filters=OFF
      --mysqld=--server_audit_syslog_facility=LOG_USER
      --mysqld=--server_audit_syslog_ident=mysql-server_auditing
      --mysqld=--server_audit_syslog_info=
      --mysqld=--server_audit_syslog_priority=LOG_INFO
      --mysqld=--server_audit_timestamp_format=%Y%m%d %H:%i:%s
      --mysqld=--shutdown_wait_for_slaves=ON
      --mysqld=--simple_password_check_digits=1
      --mysqld=--simple_password_check_letters_same_case=1
      --mysqld=--simple_password_check_minimal_length=15
      --mysqld=--simple_password_check_other_characters=1
      --mysqld=--slave_net_timeout=10
      --mysqld=--slave_parallel_max_queued=67108864
      --mysqld=--slave_parallel_threads=4
      --mysqld=--slave_parallel_workers=4
      --mysqld=--slow_query_log=ON
      --mysqld=--sql_error_log_rate=1
      --mysqld=--sql_error_log_rotate=OFF
      --mysqld=--sql_error_log_rotations=9
      --mysqld=--sql_error_log_size_limit=268435456
      --mysqld=--sql_error_log_with_db_and_thread_info=OFF
      --mysqld=--sql_mode=PIPES_AS_CONCAT,ANSI_QUOTES,IGNORE_SPACE,ORACLE,NO_KEY_OPTIONS,NO_TABLE_OPTIONS,NO_FIELD_OPTIONS,STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,SIMULTANEOUS_ASSIGNMENT
      --mysqld=--sync_binlog=1
      --mysqld=--sync_master_info=1
      --mysqld=--table_definition_cache=16384
      --mysqld=--table_open_cache=16384
      --mysqld=--thread_cache_size=256
      --mysqld=--thread_pool_size=16
      --mysqld=--thread_stack=262144
      --mysqld=--tmp_memory_table_size=33554432
      --mysqld=--tmp_table_size=33554432
      --mysqld=--transaction_isolation=READ-COMMITTED
      --mysqld=--use_stat_tables=PREFERABLY
      --mysqld=--userstat=ON
      --mysqld=--wait_timeout=3600
      --mysqld=--plugin-load-add=server_audit2
      --mysqld=--plugin-load-add=simple_password_check
      --mysqld=--plugin-load-add=sql_errlog
      --server1-mysqld=--read_only=OFF
      --server2-mysqld=--read_only=ON
      --server1-mysqld=--innodb_log_group_home_dir=$ENV{WORKSPACE}/2-1/mariadb/data
      --server1-mysqld=--log_bin_basename=$ENV{WORKSPACE}/2-1/mariadb/bin/logs/bin_logs/bin_log
      --server1-mysqld=--log_bin_index=$ENV{WORKSPACE}/2-1/mariadb/bin/logs/bin_logs/master_bin_log.index
      --server1-mysqld=--log_error=$ENV{WORKSPACE}/2-1/mariadb/bin/logs/db_logs/error_mariadb.log
      --server1-mysqld=--server_audit_file_path=$ENV{WORKSPACE}/2-1/mariadb/bin/logs/audit_logs/audit_mariadb.log
      --server1-mysqld=--slave_load_tmpdir=$ENV{WORKSPACE}/2-1/mariadb/tmp
      --server1-mysqld=--slow_query_log_file=$ENV{WORKSPACE}/2-1/mariadb/bin/logs/db_logs/slow_query_mariadb.log
      --server1-mysqld=--sql_error_log_filename=$ENV{WORKSPACE}/2-1/mariadb/bin/logs/db_logs/sql_error_mariadb.log
      --server1-mysqld=--tmpdir=$ENV{WORKSPACE}/2-1/mariadb/tmp
      --server1-mysqld=--wsrep_data_home_dir=$ENV{WORKSPACE}/2-1/mariadb/data/
      --server2-mysqld=--innodb_log_group_home_dir=$ENV{WORKSPACE}/2-2/mariadb/data
      --server2-mysqld=--log_bin_basename=$ENV{WORKSPACE}/2-2/mariadb/bin/logs/bin_logs/bin_log
      --server2-mysqld=--log_bin_index=$ENV{WORKSPACE}/2-2/mariadb/bin/logs/bin_logs/master_bin_log.index
      --server2-mysqld=--log_error=$ENV{WORKSPACE}/2-2/mariadb/bin/logs/db_logs/error_mariadb.log
      --server2-mysqld=--server_audit_file_path=$ENV{WORKSPACE}/2-2/mariadb/bin/logs/audit_logs/audit_mariadb.log
      --server2-mysqld=--slave_load_tmpdir=$ENV{WORKSPACE}/2-2/mariadb/tmp
      --server2-mysqld=--slow_query_log_file=$ENV{WORKSPACE}/2-2/mariadb/bin/logs/db_logs/slow_query_mariadb.log
      --server2-mysqld=--sql_error_log_filename=$ENV{WORKSPACE}/2-2/mariadb/bin/logs/db_logs/sql_error_mariadb.log
      --server2-mysqld=--tmpdir=$ENV{WORKSPACE}/2-2/mariadb/tmp
      --server2-mysqld=--wsrep_data_home_dir=$ENV{WORKSPACE}/2-2/mariadb/data/
  '],
  ['
      --server1-basedir=$ENV{WORKSPACE}/10.5.29-23
      --scenario=NormalUpgrades
      --threads=1
      --duration=60
      --queries=10
  '],
  ['
      --server1-basedir=$ENV{WORKSPACE}/10.5.29-23
      --scenario=Replication
      --duration=300
      --threads=4
  '],
];
