$combinations = [
  [
  '
    --threads=1
    --duration=350
    --no-mask
    --seed=time
    --grammar=conf/mariadb/modules/acl.yy
    --filter=conf/mariadb/10.4-combo-filter.ff
    --scenario=AclUpgrade
    --reporters=Backtrace,ErrorLog,Deadlock
    --mysqld=--log_output=FILE
    --mysqld=--loose-max-statement-time=10
    --mysqld=--lock-wait-timeout=5
    --mysqld=--innodb-lock-wait-timeout=3
    --mysqld=--loose-debug_assert_on_not_freed_memory=0
  '],
  [
    '',
    '
      --mysqld=--loose-plugin-load-add=auth_pam
      --mysqld=--loose-plugin-load-add=auth_socket
      --mysqld=--loose-plugin-load-add=auth_ed25519
    '
  ],
  [
    '',
    '
      --views
      --redefine=conf/mariadb/sp.yy
      --redefine=conf/mariadb/modules/admin.yy
      --redefine=conf/mariadb/modules/userstat.yy
      --redefine=conf/mariadb/modules/sql_mode.yy
      --redefine=conf/mariadb/modules/locks.yy
    '
  ],
];
