my $innodb_encryption= '--mysqld=--innodb-encrypt-tables --mysqld=--innodb-encrypt-log --mysqld=--innodb-encryption-threads=4 --mysqld=--file-key-management --mysqld=--file-key-management-filename='.$ENV{RQG_HOME}.'/data/file_key_management_keys.txt --mysqld=--plugin-load-add=file_key_management';

my $general_encryption= '--mysqld=--encrypt-tmp-disk-tables=1 --mysqld=--encrypt-tmp-files=1 --mysqld=--encrypt-binlog --mysqld=--file-key-management --mysqld=--file-key-management-filename='.$ENV{RQG_HOME}.'/data/file_key_management_keys.txt --mysqld=--plugin-load-add=file_key_management';

$combinations = [
  ##### Common options
  ['
    --duration=350
    --seed=time
    --reporters=Backtrace,ErrorLog,Deadlock
    --mysqld=--log_output=FILE
    --mysqld=--max-statement-time=30
    --mysqld=--lock-wait-timeout=10
    --mysqld=--innodb-lock-wait-timeout=5
  '],
  ##### Views
  [ '--views', '--views=MERGE', '--views=TEMPTABLE', '', '', '' ],
  ##### Virtual columns
  [ '--vcols', '--vcols=VIRTUAL', '--vcols=STORED', '--vcols=STORED', '', '', '', '', '', '' ],
  ##### Threads and number of queries
  [
    '--threads=1 --queries=100000',
    '--threads=2 --queries=50000',
    '--threads=3 --queries=33333',
    '--threads=4 --queries=25000',
    '--threads=8 --queries=12500'
  ],
  [
    {
      ##### Grammars which require specific gendata
      grammars => [
        '--grammar=conf/runtime/metadata_stability.yy --gendata=conf/runtime/metadata_stability.zz',
        '--grammar=conf/engines/many_indexes.yy --gendata=conf/engines/many_indexes.zz',
        '--grammar=conf/partitioning/partition_pruning.yy --gendata=conf/partitioning/partition_pruning.zz',
        '--grammar=conf/replication/replication.yy --gendata=conf/replication/replication-5.1.zz',
        '--grammar=conf/replication/replication-ddl_sql.yy --gendata=conf/replication/replication-ddl_data.zz',
        '--grammar=conf/replication/replication-dml_sql.yy --gendata=conf/replication/replication-dml_data.zz',
        '--grammar=conf/runtime/connect_kill_sql.yy --gendata=conf/runtime/connect_kill_data.zz',
        '--grammar=conf/runtime/WL5004_sql.yy --gendata=conf/runtime/WL5004_data.zz',
        '--grammar=conf/mariadb/oltp-transactional.yy --gendata=conf/mariadb/oltp.zz',
        '--grammar=conf/mariadb/oltp.yy --gendata=conf/mariadb/oltp.zz',
        '--grammar=conf/runtime/alter_online.yy --gendata=conf/runtime/alter_online.zz',
        '--grammar=conf/mariadb/range_access.yy --gendata=conf/optimizer/range_access.zz',
        '--grammar=conf/dyncol/dyncol_dml.yy --gendata=conf/dyncol/dyncol_dml.zz',
        "--grammar=conf/optimizer/multi_update_delete.yy --gendata",
        "--grammar=conf/optimizer/optimizer_access_exp.yy --gendata=conf/optimizer/range_access.zz",
        "--grammar=conf/optimizer/optimizer_no_subquery.yy --gendata",
        "--grammar=conf/optimizer/optimizer_subquery_semijoin.yy --gendata",
        "--grammar=conf/optimizer/optimizer_subquery.yy --gendata",
        "--grammar=conf/optimizer/outer_join.yy --gendata=conf/optimizer/outer_join.zz",
        "--grammar=conf/optimizer/range_access2.yy --gendata=conf/optimizer/range_access2.zz",
        "--grammar=conf/optimizer/range_access.yy --gendata=conf/optimizer/range_access.zz",
        "--grammar=conf/optimizer/updateable_views.yy --gendata=$ENV{RQG_HOME}/conf/optimizer/updateable_views.init",
        "--grammar=conf/dbt3/dbt3-dml.yy --gendata=$ENV{RQG_HOME}/conf/dbt3/dbt3-s0.001.dump",
        "--grammar=conf/dbt3/dbt3-joins.yy --gendata=$ENV{RQG_HOME}/conf/dbt3/dbt3-s0.001.dump",
        "--grammar=conf/dbt3/dbt3-ranges.yy --gendata=$ENV{RQG_HOME}/conf/dbt3/dbt3-s0.001.dump",
      ],
      ##### Generic grammars with various gendata
      gendata => [
        [ '--short-column-names' ],
        ##### GendataSimple, GendataAdvanced
        [ '--gendata',
          '--gendata-advanced', '--gendata-advanced', '--gendata-advanced', '--gendata-advanced',
          '--gendata-advanced --partitions', '--gendata-advanced --partitions', '--gendata-advanced --partitions',
          '--skip-gendata --gendata-advanced'
        ],
        [
          '--grammar=conf/mariadb/optimizer.yy',
          '--grammar=conf/mariadb/oltp-transactional.yy',
          '--grammar=conf/mariadb/oltp_and_ddl.yy',
          '--grammar=conf/mariadb/generic-dml.yy',
          '--grammar=conf/mariadb/multi_update.yy',
          '--grammar=conf/partitioning/partitions.yy',
        ],
        [
          '--gendata=conf/engines/maria/maria.zz',
          '--gendata=conf/engines/engine_stress.zz',
          '--gendata=conf/engines/falcon/falcon_pagesize2K.zz',
          '--gendata=conf/engines/falcon/falcon_backlog.zz',
          '--gendata=conf/engines/falcon/falcon_data_types.zz',
          '--gendata=conf/engines/falcon/falcon_pagesize32K.zz',
          '--gendata=conf/engines/falcon/falcon_data_types_no_year_time.zz',
          '--gendata=conf/engines/falcon/falcon_recovery.zz',
          '--gendata=conf/engines/falcon/falcon_chill_thaw.zz',
          '--gendata=conf/engines/falcon/falcon_blobs.zz',
          '--gendata=conf/engines/falcon/falcon_replication.zz',
          '--gendata=conf/engines/innodb/full_text_search.zz',
          '--gendata=conf/engines/tiny_inserts.zz',
          '--gendata=conf/engines/many_indexes.zz',
          '--gendata=conf/engines/handler.zz',
          '--gendata=conf/engines/varchar.zz',
          '--gendata=conf/runtime/connect_kill_data.zz',
          '--gendata=conf/runtime/metadata_stability.zz',
          '--gendata=conf/runtime/WL5004_data.zz',
          '--gendata=conf/runtime/concurrency_1.zz',
          '--gendata=conf/runtime/percona/AL-19549.zz',
          '--gendata=conf/runtime/percona/percona_qa.zz',
          '--gendata=conf/runtime/percona/AL-19549-part.zz',
          '--gendata=conf/runtime/percona/percona_qa_part.zz',
          '--gendata=conf/runtime/alter_online.zz',
          '--gendata=conf/transactions/combinations.zz',
          '--gendata=conf/transactions/transactions.zz',
          '--gendata=conf/partitioning/partition_pruning.zz',
          '--gendata=conf/examples/example.zz',
          '--gendata=conf/dyncol/dyncol_dml.zz',
          '--gendata=conf/percona/translog_percona.zz',
          '--gendata=conf/percona/percona_no_blob.zz',
          '--gendata=conf/percona/many_indexes_percona.zz',
          '--gendata=conf/percona/percona.zz',
          '--gendata=conf/percona/outer_join_percona.zz',
          '--gendata=conf/percona/query_cache_strip_comments.zz',
          '--gendata=conf/percona/innodb_dict_size_limit.zz',
          '--gendata=conf/percona/bug826632.zz',
          '--gendata=conf/replication/replication-6.0.zz',
          '--gendata=conf/replication/replication-dml_data.zz',
          '--gendata=conf/replication/replication_single_engine_pk.zz',
          '--gendata=conf/replication/rpl_transactions.zz',
          '--gendata=conf/replication/replication-5.1.zz',
          '--gendata=conf/replication/WL5092_data.zz',
          '--gendata=conf/replication/replication_single_engine.zz',
          '--gendata=conf/replication/rpl_transactions_nopk.zz',
          '--gendata=conf/replication/replication-ddl_data.zz',
          '--gendata=conf/replication/replication_innodb_myisam.zz',
          '--gendata=conf/percona_qa/AL-19549/AL-19549.zz',
          '--gendata=conf/percona_qa/percona_qa.zz',
          '--gendata=conf/percona_qa/BT-16274/BT-16274.zz',
          '--gendata=conf/percona_qa/34411/34411.zz',
          '--gendata=conf/drizzle/translog_drizzle.zz',
          '--gendata=conf/drizzle/drizzle.zz',
          '--gendata=conf/drizzle/range_access_drizzle.zz',
          '--gendata=conf/drizzle/varchar_drizzle.zz',
          '--gendata=conf/drizzle/translog_ordering.zz',
          '--gendata=conf/drizzle/outer_join_drizzle.zz',
          '--gendata=conf/drizzle/drizzledump_migrate.zz',
          '--gendata=conf/drizzle/combinations_drizzle.zz',
          '--gendata=conf/drizzle/many_indexes_drizzle.zz',
          '--gendata=conf/temporal/temporal_functions-wl946.zz',
          '--gendata=conf/temporal/temporal_functions.zz',
          '--gendata=conf/temporal/temporal_ranges.zz',
          '--gendata=conf/temporal/current_timestamp.zz',
          '--gendata=conf/temporal/current_timestamp_6.zz',
          '--gendata=conf/mariadb/gtid_stress.zz',
          '--gendata=conf/mariadb/innodb.zz',
          '--gendata=conf/mariadb/upgrade/innodb.zz',
          '--gendata=conf/mariadb/upgrade/innodb-page-compression.zz',
          '--gendata=conf/mariadb/upgrade/innodb-partition.zz',
          '--gendata=conf/mariadb/upgrade/innodb-page-compression-partition.zz',
          '--gendata=conf/mariadb/optimizer_basic.zz',
          '--gendata=conf/mariadb/innodb_upgrade_compression.zz',
          '--gendata=conf/mariadb/innodb_upgrade.zz',
          '--gendata=conf/mariadb/oltp-aria.zz',
          '--gendata=conf/mariadb/optimizer_no_indexes.zz',
          '--gendata=conf/mariadb/multi_update.zz',
          '--gendata=conf/mariadb/optimizer.zz',
          '--gendata=conf/mariadb/oltp.zz',
          '--gendata=conf/mariadb/innodb_compression_encryption.zz',
          '--gendata=conf/galera/galera_stress.zz',
          '--gendata=conf/optimizer/blobs.zz',
          '--gendata=conf/optimizer/range_access2.zz',
          '--gendata=conf/optimizer/outer_join.zz',
          '--gendata=conf/optimizer/range_access.zz',
          '--gendata=conf/backup/invariant.zz',
          "--gendata=$ENV{RQG_HOME}/conf/osm/osm-schema.sql",
          "--gendata=$ENV{RQG_HOME}/conf/osm/andorra.sql",
          "--gendata=$ENV{RQG_HOME}/conf/smf/smf2.sql",
          "--gendata=$ENV{RQG_HOME}/conf/mariadb/world.sql",
          "--gendata=$ENV{RQG_HOME}/conf/optimizer/world.sql",
        ],
      ],
    }
  ],
  ##### Transformers
  [ {
      transform => [
        [ '--validators=TransformerNoComparator' ],
        [ '', '--transformers=EnableOptimizations' ],
        [ '', '--transformers=ExecuteAsCTE' ],
        [ '', '', '', '--transformers=ExecuteAsDeleteReturning' ],
        [ '', '--transformers=ExecuteAsDerived' ],
        [ '', '--transformers=ExecuteAsExcept' ],
        [ '', '--transformers=ExecuteAsExecuteImmediate' ],
        [ '', '', '--transformers=ExecuteAsFunctionTwice' ],
        [ '', '--transformers=ExecuteAsInsertSelect' ],
        [ '', '--transformers=ExecuteAsIntersect' ],
        [ '', '', '--transformers=ExecuteAsPreparedThrice' ],
        [ '', '--transformers=ExecuteAsUpdateDelete' ],
        [ '', '--transformers=ExecuteAsUnion' ],
        [ '', '--transformers=ExecuteAsView' ],
      ],
      notransform => [ '' ]
    }
  ],
  ##### Engines and engine=specific options
  [
    {
      engines => [
        [
          '--engine=Aria --mysqld=--default-storage-engine=Aria',
          '--engine=InnoDB,MyISAM',
          '--engine=MyISAM --mysqld=--default-storage-engine=MyISAM',
          '--engine=InnoDB,MyISAM,Aria',
          '--engine=InnoDB,MyISAM,Aria,HEAP,RocksDB --mysqld=--plugin-load-add=ha_rocksdb'
        ],
        [ '', '', '', '', '', '', '', '', '', '', '',
          '--scenario=NormalUpgrade', '--scenario=NormalUpgrade',
          '--scenario=AclUpgrade'
        ],
      ],
      innodb => [
        [ '--engine=InnoDB' ],
        [ '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
          '--scenario=NormalUpgrade',
          '--scenario=CrashUpgrade',
          '--scenario=UndoLogUpgrade',
          '--scenario=MariaBackupFull',
          '--scenario=MariaBackupIncremental',
        ],
        # Default zlib
        [ '', '', '', '', '', '', '', '',
          '--mysqld=--innodb-compression-algorithm=none',
          '--mysqld=--innodb-compression-algorithm=zlib'
        ],
        [ '', '', '', '', '', '', '', '', '',
          '--mysqld=--enforce-storage-engine=InnoDB'
        ],
        # Default OFF
        [ '', '', '', '', '', '', $innodb_encryption ],
     ##### Read-only variables (InnoDB)
        # Default 8
        [ '', '', '', '', '', '', '',
          '--mysqld=--innodb-adaptive-hash-index-parts=1',
          '--mysqld=--innodb-adaptive-hash-index-parts=64',
          '--mysqld=--innodb-adaptive-hash-index-parts=512'
        ],
        # Default 1
        [ '', '', '', '', '', '', '',
          '--mysqld=--innodb-autoinc-lock-mode=0',
          '--mysqld=--innodb-autoinc-lock-mode=1',
          '--mysqld=--innodb-autoinc-lock-mode=2',
        ],
        # Default ON
        [ '', '', '', '',
          '--mysqld=--skip-innodb-doublewrite',
        ],
        # Default fsync
        [ '', '', '', '', '', '', '', '',
          '--mysqld=--innodb-flush-method=O_DSYNC',
          '--mysqld=--innodb-flush-method=littlesync',
          '--mysqld=--innodb-flush-method=nosync',
          '--mysqld=--innodb-flush-method=O_DIRECT',
          '--mysqld=--innodb-flush-method=O_DIRECT_NO_FSYNC',
        ],
        # Default fcfs
        [ '', '', '', '',
          '--mysqld=--innodb-lock-schedule-algorithm=vats'
        ],
        # Default 16M
        [ '', '', '', '', '', '', '', '',
          '--mysqld=--innodb-log-buffer-size=1M',
          '--mysqld=--innodb-log-buffer-size=128M',
        ],
        # Default 50M
        [ '', '', '', '', '', '', '', '',
          '--mysqld=--innodb-log-file-size=16M',
          '--mysqld=--innodb-log-file-size=256M',
        ],
        # Default 0
        [ '', '', '', '', '', '', '', '',
          '--mysqld=--innodb-open-files=200',
          '--mysqld=--innodb-open-files=10000',
        ],
        # Default 16K
        [ '', '', '', '', '', '',
          '--mysqld=--innodb-page-size=4K',
          '--mysqld=--innodb-page-size=8K',
          '--mysqld=--innodb-page-size=32K',
          '--mysqld=--innodb-page-size=64K',
        ],
        # Default 4
        [ '', '', '', '',
          '--mysqld=--innodb-purge-threads=1',
          '--mysqld=--innodb-purge-threads=32',
        ],
        # Default 4
        [ '', '', '', '',
          '--mysqld=--innodb-read-io-threads=1',
          '--mysqld=--innodb-read-io-threads=16',
        ],
        # Default 1M
        [ '', '', '', '',
          '--mysqld=--innodb-sort-buffer-size=64K',
          '--mysqld=--innodb-sort-buffer-size=64M',
        ],
        # Default 1
        [ '', '', '', '',
          '--mysqld=--innodb-sync-array-size=8',
          '--mysqld=--innodb-sync-array-size=128',
        ],
        # Default 0
        [ '', '', '', '', '', '', '',
          '--mysqld=--innodb-undo-tablespaces=1',
          '--mysqld=--innodb-undo-tablespaces=2',
          '--mysqld=--innodb-undo-tablespaces=127',
        ],
        # Default ON
        [ '', '', '', '', '', '', '', '', '',
          '--mysqld=--innodb-use-atomic-writes=OFF'
        ],
        # Default ON
        [ '', '', '', '', '', '', '', '', '',
          '--mysqld=--innodb-use-native-aio=OFF'
        ],
        # Default 4
        [ '', '', '', '',
          '--mysqld=--innodb-write-io-threads=2',
          '--mysqld=--innodb-write-io-threads=16',
        ],
      ],
    }
  ],
  ##### Redefines
  [
    [ '--redefine=conf/mariadb/alter_table.yy', '', '', '', '' ],
    [ '--redefine=conf/mariadb/bulk_insert.yy', '' ],
    [ '--redefine=conf/mariadb/federated.yy --mysqld=--plugin-load-add=ha_federatedx', '', '', '', '', '', '', '', '', '' ],
    [ '--redefine=conf/mariadb/functions.yy', '', '', '', '' ],
    [ '--redefine=conf/mariadb/json.yy', '', '', '', '' ],
    [ '--redefine=conf/mariadb/sequences.yy', '', '', '', '', '', '', '', '', '' ],
    [ '--redefine=conf/mariadb/sp.yy', '', '', '', '' ],
    [ '--redefine=conf/mariadb/versioning.yy', '', '', '', '', '', '', '', '', '' ],
    [ '--redefine=conf/mariadb/xa.yy', '', '', '', '', '', '', '', '', '' ],
    [ '--redefine=conf/mariadb/modules/acl.yy', '', '', '', '', '', '', '', '', '' ],
    [ '--redefine=conf/mariadb/modules/admin.yy', '', '', '', '' ],
    [ '--redefine=conf/mariadb/modules/alter_table_columns.yy', '', '', '', '' ],
    [ '--redefine=conf/mariadb/modules/alter_table_indexes.yy', '', '', '', '' ],
    [ '--redefine=conf/mariadb/modules/application_periods.yy', '', '', '', '', '', '', '', '', '' ],
    [ '--redefine=conf/mariadb/modules/disks.yy', '', '', '', '', '', '', '', '', '' ],
    [ '--redefine=conf/mariadb/modules/dynamic_variables.yy', '' ],
    [ '--redefine=conf/mariadb/modules/event.yy', '', '', '', '', '', '', '', '', '' ],
    [ '--redefine=conf/mariadb/modules/foreign_keys.yy', '', '', '', '' ],
    [ '--redefine=conf/mariadb/modules/indexes_and_constraints.yy', '', '', '', '' ],
    [ '--redefine=conf/mariadb/modules/information_schema.yy', '', '', '', '', '' ],
    [ '--redefine=conf/mariadb/modules/locales.yy', '', '', '', '', '', '', '', '', '' ],
    [ '--redefine=conf/mariadb/modules/locks.yy', '', '', '', '' ],
    [ '--redefine=conf/mariadb/modules/locks-10.4-extra.yy', '', '', '', '' ],
    [ '--redefine=conf/mariadb/modules/metadata_lock_info.yy', '', '', '', '' ],
    [ '--redefine=conf/mariadb/modules/optimizer_trace.yy', '', '', '' ],
    [ '--redefine=conf/mariadb/modules/parser_changes.yy', '', '', '', '' ],
    [ '--redefine=conf/mariadb/modules/query_response_time.yy', '', '', '', '', '', '', '', '', '' ],
    [ '--redefine=conf/mariadb/modules/server_audit.yy', '', '', '', '', '', '', '', '', '' ],
    [ '--redefine=conf/mariadb/modules/sql_errlog.yy', '', '', '', '', '', '', '', '', '' ],
    [ '--redefine=conf/mariadb/modules/userstat.yy', '', '', '', '', '', '', '', '', '' ],
    [ '--redefine=conf/mariadb/modules/user_variables.yy', '', '', '', '', '', '', '', '', '' ],
  ],
  ##### Plugins
  [
    [ '--mysqld=--plugin-load-add=ha_archive', '', '', '', '', '', '', '', '', '' ],
    [ '--mysqld=--plugin-load-add=ha_blackhole', '', '', '', '', '', '', '', '', '' ],
    [ '--mysqld=--plugin-load-add=query_cache_info', '', '', '', '' ],
    [ '--mysqld=--plugin-load-add=simple_password_check', '', '', '', '' ],
  ],
  ##### PS protocol
  [ '--ps-protocol --filter=conf/mariadb/need-reconnect.ff', '', '', '', '' ],
  ##### Encryption
  [ '', '', '', '', $general_encryption ],
  ##### Binary logging
  [ '', '',
    [
      [ '--mysqld=--log-bin --mysqld=--log_bin_trust_function_creators=1' ],
      [ '--mysqld=--binlog-format=row', '--mysqld=--binlog-format=mixed' ],
    ]
  ],
  ##### Performance schema
  [ '', '', '',
    "--mysqld=--performance-schema=on
     --mysqld=--performance-schema-instrument='%=ON'
     --mysqld=--performance-schema-consumer-events-stages-current=ON
     --mysqld=--performance-schema-consumer-events-stages-history=ON
     --mysqld=--performance-schema-consumer-events-stages-history-long=ON
     --mysqld=--performance-schema-consumer-events-statements-current=ON
     --mysqld=--performance-schema-consumer-events-statements-history=ON
     --mysqld=--performance-schema-consumer-events-statements-history-long=ON
     --mysqld=--performance-schema-consumer-events-waits-current=ON
     --mysqld=--performance-schema-consumer-events-waits-history=ON
     --mysqld=--performance-schema-consumer-events-waits-history-long=ON
     --mysqld=--performance-schema-consumer-global-instrumentation=ON
     --mysqld=--performance-schema-consumer-thread-instrumentation=ON
     --mysqld=--performance-schema-consumer-statements-digest=ON
     --redefine=conf/runtime/performance_schema.yy"
  ],
  ##### Read-only variables (general)
  # Default OFF
  [ '', '', '', '', '--mysqld=--explicit-defaults-for-timestamp=on' ],
  # Default OFF
  [ '', '', '', '', '--mysqld=--large-pages=on' ],
  # Default 24K
  [ '', '', '', '', '', '', '', '',
    '--mysqld=--log-tc-size=12K',
    '--mysqld=--log-tc-size=1M',
  ],
  # Default 0
  [ '', '', '', '', '', '--mysqld=--lower-case-table-names=1' ],
  # Default 1024
  [ '', '', '', '', '', '', '',
    '--mysqld=--max-digest-length=0',
    '--mysqld=--max-digest-length=64',
    '--mysqld=--max-digest-length=1M',
  ],
  # Default NO
  [ '', '', '', '', '', '', '', '',
    '--mysqld=--secure-timestamp=SUPER',
    '--mysqld=--secure-timestamp=REPLICATION',
    '--mysqld=--secure-timestamp=YES',
  ],
  # Default ON
  [ '', '', '', '', '', '', '', '', '',
    '--mysqld=--skip-external-locking=OFF',
  ],
  # Default OFF
  [ '', '', '', '', '', '', '', '', '',
    '--mysqld=--skip-show-database=ON',
  ],
  # Default 8
  [ '', '', '', '', '', '', '', '',
    '--mysqld=--table-open-cache-instances=1',
    '--mysqld=--table-open-cache-instances=64',
  ],
  # Default one-thread-per-connection (on Linux)
  [ '', '', '',
    '--mysqld=--thread-handling=pool-of-threads',
  ],
  # Default 299008 (machine/build-dependent?)
  [ '', '', '', '', '', '', '', '',
    '--mysqld=--thread-stack=131072',
    '--mysqld=--thread-stack=1M',
  ],
  ##### Character sets
  # Default depends on the build/system, so in addition to the default,
  # we'll also add extra utf8 with presumably most common collations
  #   Workarounds:
  #   - swe7 disabled due to MDEV-24591
  #   '--mysqld=--character-set-server=swe7 --mysqld=--collation-server=swe7_swedish_ci',
  #   '--mysqld=--character-set-server=swe7 --mysqld=--collation-server=swe7_bin',
  #   '--mysqld=--character-set-server=swe7 --mysqld=--collation-server=swe7_swedish_nopad_ci',
  #   '--mysqld=--character-set-server=swe7 --mysqld=--collation-server=swe7_nopad_bin',
  [
    '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
    '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
    '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_general_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_general_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_general_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_general_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_general_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_bin',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_bin',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_bin',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_unicode_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_unicode_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_general_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_general_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_general_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_general_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_general_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_bin',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_bin',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_bin',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_unicode_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_unicode_ci',
    '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
    '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
    '--mysqld=--character-set-server=big5 --mysqld=--collation-server=big5_chinese_ci',
    '--mysqld=--character-set-server=big5 --mysqld=--collation-server=big5_bin',
    '--mysqld=--character-set-server=big5 --mysqld=--collation-server=big5_chinese_nopad_ci',
    '--mysqld=--character-set-server=big5 --mysqld=--collation-server=big5_nopad_bin',
    '--mysqld=--character-set-server=dec8 --mysqld=--collation-server=dec8_swedish_ci',
    '--mysqld=--character-set-server=dec8 --mysqld=--collation-server=dec8_bin',
    '--mysqld=--character-set-server=dec8 --mysqld=--collation-server=dec8_swedish_nopad_ci',
    '--mysqld=--character-set-server=dec8 --mysqld=--collation-server=dec8_nopad_bin',
    '--mysqld=--character-set-server=cp850 --mysqld=--collation-server=cp850_general_ci',
    '--mysqld=--character-set-server=cp850 --mysqld=--collation-server=cp850_bin',
    '--mysqld=--character-set-server=cp850 --mysqld=--collation-server=cp850_general_nopad_ci',
    '--mysqld=--character-set-server=cp850 --mysqld=--collation-server=cp850_nopad_bin',
    '--mysqld=--character-set-server=hp8 --mysqld=--collation-server=hp8_english_ci',
    '--mysqld=--character-set-server=hp8 --mysqld=--collation-server=hp8_bin',
    '--mysqld=--character-set-server=hp8 --mysqld=--collation-server=hp8_english_nopad_ci',
    '--mysqld=--character-set-server=hp8 --mysqld=--collation-server=hp8_nopad_bin',
    '--mysqld=--character-set-server=koi8r --mysqld=--collation-server=koi8r_general_ci',
    '--mysqld=--character-set-server=koi8r --mysqld=--collation-server=koi8r_bin',
    '--mysqld=--character-set-server=koi8r --mysqld=--collation-server=koi8r_general_nopad_ci',
    '--mysqld=--character-set-server=koi8r --mysqld=--collation-server=koi8r_nopad_bin',
    '--mysqld=--character-set-server=latin1 --mysqld=--collation-server=latin1_german1_ci',
    '--mysqld=--character-set-server=latin1 --mysqld=--collation-server=latin1_swedish_ci',
    '--mysqld=--character-set-server=latin1 --mysqld=--collation-server=latin1_danish_ci',
    '--mysqld=--character-set-server=latin1 --mysqld=--collation-server=latin1_german2_ci',
    '--mysqld=--character-set-server=latin1 --mysqld=--collation-server=latin1_bin',
    '--mysqld=--character-set-server=latin1 --mysqld=--collation-server=latin1_general_ci',
    '--mysqld=--character-set-server=latin1 --mysqld=--collation-server=latin1_general_cs',
    '--mysqld=--character-set-server=latin1 --mysqld=--collation-server=latin1_spanish_ci',
    '--mysqld=--character-set-server=latin1 --mysqld=--collation-server=latin1_swedish_nopad_ci',
    '--mysqld=--character-set-server=latin1 --mysqld=--collation-server=latin1_nopad_bin',
    '--mysqld=--character-set-server=latin2 --mysqld=--collation-server=latin2_czech_cs',
    '--mysqld=--character-set-server=latin2 --mysqld=--collation-server=latin2_general_ci',
    '--mysqld=--character-set-server=latin2 --mysqld=--collation-server=latin2_hungarian_ci',
    '--mysqld=--character-set-server=latin2 --mysqld=--collation-server=latin2_croatian_ci',
    '--mysqld=--character-set-server=latin2 --mysqld=--collation-server=latin2_bin',
    '--mysqld=--character-set-server=latin2 --mysqld=--collation-server=latin2_general_nopad_ci',
    '--mysqld=--character-set-server=latin2 --mysqld=--collation-server=latin2_nopad_bin',
    '--mysqld=--character-set-server=ascii --mysqld=--collation-server=ascii_general_ci',
    '--mysqld=--character-set-server=ascii --mysqld=--collation-server=ascii_bin',
    '--mysqld=--character-set-server=ascii --mysqld=--collation-server=ascii_general_nopad_ci',
    '--mysqld=--character-set-server=ascii --mysqld=--collation-server=ascii_nopad_bin',
    '--mysqld=--character-set-server=ujis --mysqld=--collation-server=ujis_japanese_ci',
    '--mysqld=--character-set-server=ujis --mysqld=--collation-server=ujis_bin',
    '--mysqld=--character-set-server=ujis --mysqld=--collation-server=ujis_japanese_nopad_ci',
    '--mysqld=--character-set-server=ujis --mysqld=--collation-server=ujis_nopad_bin',
    '--mysqld=--character-set-server=sjis --mysqld=--collation-server=sjis_japanese_ci',
    '--mysqld=--character-set-server=sjis --mysqld=--collation-server=sjis_bin',
    '--mysqld=--character-set-server=sjis --mysqld=--collation-server=sjis_japanese_nopad_ci',
    '--mysqld=--character-set-server=sjis --mysqld=--collation-server=sjis_nopad_bin',
    '--mysqld=--character-set-server=hebrew --mysqld=--collation-server=hebrew_general_ci',
    '--mysqld=--character-set-server=hebrew --mysqld=--collation-server=hebrew_bin',
    '--mysqld=--character-set-server=hebrew --mysqld=--collation-server=hebrew_general_nopad_ci',
    '--mysqld=--character-set-server=hebrew --mysqld=--collation-server=hebrew_nopad_bin',
    '--mysqld=--character-set-server=tis620 --mysqld=--collation-server=tis620_thai_ci',
    '--mysqld=--character-set-server=tis620 --mysqld=--collation-server=tis620_bin',
    '--mysqld=--character-set-server=tis620 --mysqld=--collation-server=tis620_thai_nopad_ci',
    '--mysqld=--character-set-server=tis620 --mysqld=--collation-server=tis620_nopad_bin',
    '--mysqld=--character-set-server=euckr --mysqld=--collation-server=euckr_korean_ci',
    '--mysqld=--character-set-server=euckr --mysqld=--collation-server=euckr_bin',
    '--mysqld=--character-set-server=euckr --mysqld=--collation-server=euckr_korean_nopad_ci',
    '--mysqld=--character-set-server=euckr --mysqld=--collation-server=euckr_nopad_bin',
    '--mysqld=--character-set-server=koi8u --mysqld=--collation-server=koi8u_general_ci',
    '--mysqld=--character-set-server=koi8u --mysqld=--collation-server=koi8u_bin',
    '--mysqld=--character-set-server=koi8u --mysqld=--collation-server=koi8u_general_nopad_ci',
    '--mysqld=--character-set-server=koi8u --mysqld=--collation-server=koi8u_nopad_bin',
    '--mysqld=--character-set-server=gb2312 --mysqld=--collation-server=gb2312_chinese_ci',
    '--mysqld=--character-set-server=gb2312 --mysqld=--collation-server=gb2312_bin',
    '--mysqld=--character-set-server=gb2312 --mysqld=--collation-server=gb2312_chinese_nopad_ci',
    '--mysqld=--character-set-server=gb2312 --mysqld=--collation-server=gb2312_nopad_bin',
    '--mysqld=--character-set-server=greek --mysqld=--collation-server=greek_general_ci',
    '--mysqld=--character-set-server=greek --mysqld=--collation-server=greek_bin',
    '--mysqld=--character-set-server=greek --mysqld=--collation-server=greek_general_nopad_ci',
    '--mysqld=--character-set-server=greek --mysqld=--collation-server=greek_nopad_bin',
    '--mysqld=--character-set-server=cp1250 --mysqld=--collation-server=cp1250_general_ci',
    '--mysqld=--character-set-server=cp1250 --mysqld=--collation-server=cp1250_czech_cs',
    '--mysqld=--character-set-server=cp1250 --mysqld=--collation-server=cp1250_croatian_ci',
    '--mysqld=--character-set-server=cp1250 --mysqld=--collation-server=cp1250_bin',
    '--mysqld=--character-set-server=cp1250 --mysqld=--collation-server=cp1250_polish_ci',
    '--mysqld=--character-set-server=cp1250 --mysqld=--collation-server=cp1250_general_nopad_ci',
    '--mysqld=--character-set-server=cp1250 --mysqld=--collation-server=cp1250_nopad_bin',
    '--mysqld=--character-set-server=gbk --mysqld=--collation-server=gbk_chinese_ci',
    '--mysqld=--character-set-server=gbk --mysqld=--collation-server=gbk_bin',
    '--mysqld=--character-set-server=gbk --mysqld=--collation-server=gbk_chinese_nopad_ci',
    '--mysqld=--character-set-server=gbk --mysqld=--collation-server=gbk_nopad_bin',
    '--mysqld=--character-set-server=latin5 --mysqld=--collation-server=latin5_turkish_ci',
    '--mysqld=--character-set-server=latin5 --mysqld=--collation-server=latin5_bin',
    '--mysqld=--character-set-server=latin5 --mysqld=--collation-server=latin5_turkish_nopad_ci',
    '--mysqld=--character-set-server=latin5 --mysqld=--collation-server=latin5_nopad_bin',
    '--mysqld=--character-set-server=armscii8 --mysqld=--collation-server=armscii8_general_ci',
    '--mysqld=--character-set-server=armscii8 --mysqld=--collation-server=armscii8_bin',
    '--mysqld=--character-set-server=armscii8 --mysqld=--collation-server=armscii8_general_nopad_ci',
    '--mysqld=--character-set-server=armscii8 --mysqld=--collation-server=armscii8_nopad_bin',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_general_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_bin',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_unicode_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_icelandic_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_latvian_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_romanian_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_slovenian_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_polish_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_estonian_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_spanish_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_swedish_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_turkish_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_czech_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_danish_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_lithuanian_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_slovak_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_spanish2_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_roman_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_persian_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_esperanto_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_hungarian_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_sinhala_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_german2_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_croatian_mysql561_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_unicode_520_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_vietnamese_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_general_mysql500_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_croatian_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_myanmar_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_thai_520_w2',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_general_nopad_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_nopad_bin',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_unicode_nopad_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_unicode_520_nopad_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_general_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_bin',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_unicode_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_icelandic_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_latvian_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_romanian_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_slovenian_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_polish_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_estonian_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_spanish_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_swedish_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_turkish_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_czech_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_danish_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_lithuanian_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_slovak_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_spanish2_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_roman_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_persian_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_esperanto_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_hungarian_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_sinhala_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_german2_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_croatian_mysql561_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_unicode_520_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_vietnamese_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_general_mysql500_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_croatian_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_myanmar_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_thai_520_w2',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_general_nopad_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_nopad_bin',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_unicode_nopad_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_unicode_520_nopad_ci',
    '--mysqld=--character-set-server=cp866 --mysqld=--collation-server=cp866_general_ci',
    '--mysqld=--character-set-server=cp866 --mysqld=--collation-server=cp866_bin',
    '--mysqld=--character-set-server=cp866 --mysqld=--collation-server=cp866_general_nopad_ci',
    '--mysqld=--character-set-server=cp866 --mysqld=--collation-server=cp866_nopad_bin',
    '--mysqld=--character-set-server=keybcs2 --mysqld=--collation-server=keybcs2_general_ci',
    '--mysqld=--character-set-server=keybcs2 --mysqld=--collation-server=keybcs2_bin',
    '--mysqld=--character-set-server=keybcs2 --mysqld=--collation-server=keybcs2_general_nopad_ci',
    '--mysqld=--character-set-server=keybcs2 --mysqld=--collation-server=keybcs2_nopad_bin',
    '--mysqld=--character-set-server=macce --mysqld=--collation-server=macce_general_ci',
    '--mysqld=--character-set-server=macce --mysqld=--collation-server=macce_bin',
    '--mysqld=--character-set-server=macce --mysqld=--collation-server=macce_general_nopad_ci',
    '--mysqld=--character-set-server=macce --mysqld=--collation-server=macce_nopad_bin',
    '--mysqld=--character-set-server=macroman --mysqld=--collation-server=macroman_general_ci',
    '--mysqld=--character-set-server=macroman --mysqld=--collation-server=macroman_bin',
    '--mysqld=--character-set-server=macroman --mysqld=--collation-server=macroman_general_nopad_ci',
    '--mysqld=--character-set-server=macroman --mysqld=--collation-server=macroman_nopad_bin',
    '--mysqld=--character-set-server=cp852 --mysqld=--collation-server=cp852_general_ci',
    '--mysqld=--character-set-server=cp852 --mysqld=--collation-server=cp852_bin',
    '--mysqld=--character-set-server=cp852 --mysqld=--collation-server=cp852_general_nopad_ci',
    '--mysqld=--character-set-server=cp852 --mysqld=--collation-server=cp852_nopad_bin',
    '--mysqld=--character-set-server=latin7 --mysqld=--collation-server=latin7_estonian_cs',
    '--mysqld=--character-set-server=latin7 --mysqld=--collation-server=latin7_general_ci',
    '--mysqld=--character-set-server=latin7 --mysqld=--collation-server=latin7_general_cs',
    '--mysqld=--character-set-server=latin7 --mysqld=--collation-server=latin7_bin',
    '--mysqld=--character-set-server=latin7 --mysqld=--collation-server=latin7_general_nopad_ci',
    '--mysqld=--character-set-server=latin7 --mysqld=--collation-server=latin7_nopad_bin',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_general_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_bin',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_unicode_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_icelandic_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_latvian_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_romanian_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_slovenian_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_polish_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_estonian_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_spanish_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_swedish_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_turkish_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_czech_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_danish_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_lithuanian_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_slovak_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_spanish2_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_roman_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_persian_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_esperanto_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_hungarian_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_sinhala_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_german2_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_croatian_mysql561_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_unicode_520_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_vietnamese_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_croatian_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_myanmar_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_thai_520_w2',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_general_nopad_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_nopad_bin',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_unicode_nopad_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_unicode_520_nopad_ci',
    '--mysqld=--character-set-server=cp1251 --mysqld=--collation-server=cp1251_bulgarian_ci',
    '--mysqld=--character-set-server=cp1251 --mysqld=--collation-server=cp1251_ukrainian_ci',
    '--mysqld=--character-set-server=cp1251 --mysqld=--collation-server=cp1251_bin',
    '--mysqld=--character-set-server=cp1251 --mysqld=--collation-server=cp1251_general_ci',
    '--mysqld=--character-set-server=cp1251 --mysqld=--collation-server=cp1251_general_cs',
    '--mysqld=--character-set-server=cp1251 --mysqld=--collation-server=cp1251_nopad_bin',
    '--mysqld=--character-set-server=cp1251 --mysqld=--collation-server=cp1251_general_nopad_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_general_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_bin',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_unicode_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_icelandic_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_latvian_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_romanian_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_slovenian_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_polish_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_estonian_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_spanish_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_swedish_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_turkish_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_czech_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_danish_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_lithuanian_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_slovak_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_spanish2_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_roman_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_persian_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_esperanto_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_hungarian_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_sinhala_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_german2_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_croatian_mysql561_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_unicode_520_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_vietnamese_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_croatian_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_myanmar_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_thai_520_w2',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_general_nopad_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_nopad_bin',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_unicode_nopad_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_unicode_520_nopad_ci',
    '--mysqld=--character-set-server=utf16le --mysqld=--collation-server=utf16le_general_ci',
    '--mysqld=--character-set-server=utf16le --mysqld=--collation-server=utf16le_bin',
    '--mysqld=--character-set-server=utf16le --mysqld=--collation-server=utf16le_general_nopad_ci',
    '--mysqld=--character-set-server=utf16le --mysqld=--collation-server=utf16le_nopad_bin',
    '--mysqld=--character-set-server=cp1256 --mysqld=--collation-server=cp1256_general_ci',
    '--mysqld=--character-set-server=cp1256 --mysqld=--collation-server=cp1256_bin',
    '--mysqld=--character-set-server=cp1256 --mysqld=--collation-server=cp1256_general_nopad_ci',
    '--mysqld=--character-set-server=cp1256 --mysqld=--collation-server=cp1256_nopad_bin',
    '--mysqld=--character-set-server=cp1257 --mysqld=--collation-server=cp1257_lithuanian_ci',
    '--mysqld=--character-set-server=cp1257 --mysqld=--collation-server=cp1257_bin',
    '--mysqld=--character-set-server=cp1257 --mysqld=--collation-server=cp1257_general_ci',
    '--mysqld=--character-set-server=cp1257 --mysqld=--collation-server=cp1257_nopad_bin',
    '--mysqld=--character-set-server=cp1257 --mysqld=--collation-server=cp1257_general_nopad_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_general_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_bin',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_unicode_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_icelandic_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_latvian_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_romanian_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_slovenian_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_polish_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_estonian_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_spanish_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_swedish_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_turkish_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_czech_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_danish_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_lithuanian_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_slovak_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_spanish2_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_roman_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_persian_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_esperanto_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_hungarian_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_sinhala_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_german2_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_croatian_mysql561_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_unicode_520_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_vietnamese_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_croatian_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_myanmar_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_thai_520_w2',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_general_nopad_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_nopad_bin',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_unicode_nopad_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_unicode_520_nopad_ci',
    '--mysqld=--character-set-server=binary --mysqld=--collation-server=binary',
    '--mysqld=--character-set-server=geostd8 --mysqld=--collation-server=geostd8_general_ci',
    '--mysqld=--character-set-server=geostd8 --mysqld=--collation-server=geostd8_bin',
    '--mysqld=--character-set-server=geostd8 --mysqld=--collation-server=geostd8_general_nopad_ci',
    '--mysqld=--character-set-server=geostd8 --mysqld=--collation-server=geostd8_nopad_bin',
    '--mysqld=--character-set-server=cp932 --mysqld=--collation-server=cp932_japanese_ci',
    '--mysqld=--character-set-server=cp932 --mysqld=--collation-server=cp932_bin',
    '--mysqld=--character-set-server=cp932 --mysqld=--collation-server=cp932_japanese_nopad_ci',
    '--mysqld=--character-set-server=cp932 --mysqld=--collation-server=cp932_nopad_bin',
    '--mysqld=--character-set-server=eucjpms --mysqld=--collation-server=eucjpms_japanese_ci',
    '--mysqld=--character-set-server=eucjpms --mysqld=--collation-server=eucjpms_bin',
    '--mysqld=--character-set-server=eucjpms --mysqld=--collation-server=eucjpms_japanese_nopad_ci',
    '--mysqld=--character-set-server=eucjpms --mysqld=--collation-server=eucjpms_nopad_bin',
  ],
];
