# MDEV-26519 JSON histograms
# Test run for histogram precision check (comparison against DOUBLE_PREC_HB)

$combinations = [
  ['
    --no-mask
    --seed=time
    --threads=4
    --duration=400
    --queries=100M
    --reporters=Backtrace,ErrorLog,Deadlock
    --mysqld=--log-output=FILE
    --mysqld=--max-statement-time=30
    --mysqld=--histogram_size=255
    --mysqld1=--histogram_type=JSON_HB
    --mysqld2=--histogram_type=DOUBLE_PREC_HB
    --validators=HistogramPrecisionSingleTable
    --grammar=conf/mariadb/features/histogram_single_table.yy
    --redefine=conf/mariadb/features/histogram_analyze.yy
    --rows=20,100,200,500,750,1000,2000,5000
  '],
  [ '--engine=InnoDB', '--engine=MyISAM --mysqld=--default-storage-engine=MyISAM', '--engine=Aria --mysqld=--default-storage-engine=Aria' ],
  [ '', '--notnull' ],
  [
    '--gendata',
    '--skip-gendata --gendata-advanced',
    '--gendata=conf/engines/maria/maria.zz',
    '--gendata=conf/engines/engine_stress.zz',
    '--gendata=conf/engines/falcon/falcon_pagesize2K.zz',
    '--gendata=conf/engines/falcon/falcon_data_types.zz',
    '--gendata=conf/engines/falcon/falcon_pagesize32K.zz',
    '--gendata=conf/engines/falcon/falcon_data_types_no_year_time.zz',
    '--gendata=conf/engines/falcon/falcon_recovery.zz',
    '--gendata=conf/engines/falcon/falcon_chill_thaw.zz',
    '--gendata=conf/engines/falcon/falcon_blobs.zz',
    '--gendata=conf/engines/falcon/falcon_replication.zz',
    '--gendata=conf/engines/innodb/full_text_search.zz',
    '--gendata=conf/engines/tiny_inserts.zz',
    '--gendata=conf/engines/many_indexes.zz',
    '--gendata=conf/engines/handler.zz',
    '--gendata=conf/engines/varchar.zz',
    '--gendata=conf/runtime/connect_kill_data.zz',
    '--gendata=conf/runtime/metadata_stability.zz',
    '--gendata=conf/runtime/WL5004_data.zz',
    '--gendata=conf/runtime/concurrency_1.zz',
    '--gendata=conf/runtime/percona/AL-19549.zz',
    '--gendata=conf/runtime/percona/percona_qa.zz',
    '--gendata=conf/runtime/percona/percona_qa_parts.zz',
    '--gendata=conf/runtime/percona/AL-19549-part.zz',
    '--gendata=conf/runtime/percona/percona_qa_part.zz',
    '--gendata=conf/runtime/alter_online.zz',
    '--gendata=conf/transactions/combinations.zz',
    '--gendata=conf/transactions/transactions.zz',
    '--gendata=conf/partitioning/partition_pruning.zz',
    '--gendata=conf/examples/example.zz',
    '--gendata=conf/dyncol/dyncol_dml.zz',
    '--gendata=conf/percona/translog_percona.zz',
    '--gendata=conf/percona/percona_no_blob.zz',
    '--gendata=conf/percona/many_indexes_percona.zz',
    '--gendata=conf/percona/percona.zz',
    '--gendata=conf/percona/outer_join_percona.zz',
    '--gendata=conf/percona/query_cache_strip_comments.zz',
    '--gendata=conf/percona/innodb_dict_size_limit.zz',
    '--gendata=conf/percona/bug826632.zz',
    '--gendata=conf/replication/replication-6.0.zz',
    '--gendata=conf/replication/replication-dml_data.zz',
    '--gendata=conf/replication/replication_single_engine_pk.zz',
    '--gendata=conf/replication/rpl_transactions.zz',
    '--gendata=conf/replication/replication-5.1.zz',
    '--gendata=conf/replication/WL5092_data.zz',
    '--gendata=conf/replication/replication_single_engine.zz',
    '--gendata=conf/replication/rpl_transactions_nopk.zz',
    '--gendata=conf/replication/replication-ddl_data.zz',
    '--gendata=conf/replication/replication_innodb_myisam.zz',
    '--gendata=conf/percona_qa/AL-19549/AL-19549.zz',
    '--gendata=conf/percona_qa/BT-16274/BT-16274.zz',
    '--gendata=conf/percona_qa/34411/34411.zz',
    '--gendata=conf/drizzle/translog_drizzle.zz',
    '--gendata=conf/drizzle/drizzle.zz',
    '--gendata=conf/drizzle/range_access_drizzle.zz',
    '--gendata=conf/drizzle/varchar_drizzle.zz',
    '--gendata=conf/drizzle/translog_ordering.zz',
    '--gendata=conf/drizzle/outer_join_drizzle.zz',
    '--gendata=conf/drizzle/drizzledump_migrate.zz',
    '--gendata=conf/drizzle/combinations_drizzle.zz',
    '--gendata=conf/drizzle/many_indexes_drizzle.zz',
    '--gendata=conf/temporal/temporal_functions-wl946.zz',
    '--gendata=conf/temporal/temporal_functions.zz',
    '--gendata=conf/temporal/temporal_ranges.zz',
    '--gendata=conf/temporal/current_timestamp.zz',
    '--gendata=conf/temporal/current_timestamp_6.zz',
    '--gendata=conf/mariadb/gtid_stress.zz',
    '--gendata=conf/mariadb/innodb.zz',
    '--gendata=conf/mariadb/upgrade/innodb.zz',
    '--gendata=conf/mariadb/upgrade/innodb-page-compression.zz',
    '--gendata=conf/mariadb/upgrade/innodb-partition.zz',
    '--gendata=conf/mariadb/upgrade/innodb-page-compression-partition.zz',
    '--gendata=conf/mariadb/optimizer_basic.zz',
    '--gendata=conf/mariadb/innodb_upgrade_compression.zz',
    '--gendata=conf/mariadb/innodb_upgrade.zz',
    '--gendata=conf/mariadb/oltp-aria.zz',
    '--gendata=conf/mariadb/optimizer_no_indexes.zz',
    '--gendata=conf/mariadb/multi_update.zz',
    '--gendata=conf/mariadb/optimizer.zz',
    '--gendata=conf/mariadb/oltp.zz',
    '--gendata=conf/mariadb/innodb_compression_encryption.zz',
    '--gendata=conf/galera/galera_stress.zz',
    '--gendata=conf/optimizer/blobs.zz',
    '--gendata=conf/optimizer/range_access2.zz',
    '--gendata=conf/optimizer/outer_join.zz',
    '--gendata=conf/optimizer/range_access.zz',
    '--gendata=conf/backup/invariant.zz',
    "--gendata=$ENV{RQG_HOME}/conf/osm/osm-schema.sql",
    "--gendata=$ENV{RQG_HOME}/conf/osm/andorra.sql",
    "--gendata=$ENV{RQG_HOME}/conf/smf/smf2.sql",
    "--gendata=$ENV{RQG_HOME}/conf/mariadb/world.sql",
    "--gendata=$ENV{RQG_HOME}/conf/optimizer/world.sql",
  ],
  [
    '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
    '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
    '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_general_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_general_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_general_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_general_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_general_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_bin',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_bin',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_bin',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_unicode_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_unicode_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_general_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_general_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_general_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_general_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_general_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_bin',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_bin',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_bin',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_unicode_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_unicode_ci',
    '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
    '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
    '--mysqld=--character-set-server=big5 --mysqld=--collation-server=big5_chinese_ci',
    '--mysqld=--character-set-server=big5 --mysqld=--collation-server=big5_bin',
    '--mysqld=--character-set-server=big5 --mysqld=--collation-server=big5_chinese_nopad_ci',
    '--mysqld=--character-set-server=big5 --mysqld=--collation-server=big5_nopad_bin',
    '--mysqld=--character-set-server=dec8 --mysqld=--collation-server=dec8_swedish_ci',
    '--mysqld=--character-set-server=dec8 --mysqld=--collation-server=dec8_bin',
    '--mysqld=--character-set-server=dec8 --mysqld=--collation-server=dec8_swedish_nopad_ci',
    '--mysqld=--character-set-server=dec8 --mysqld=--collation-server=dec8_nopad_bin',
    '--mysqld=--character-set-server=cp850 --mysqld=--collation-server=cp850_general_ci',
    '--mysqld=--character-set-server=cp850 --mysqld=--collation-server=cp850_bin',
    '--mysqld=--character-set-server=cp850 --mysqld=--collation-server=cp850_general_nopad_ci',
    '--mysqld=--character-set-server=cp850 --mysqld=--collation-server=cp850_nopad_bin',
    '--mysqld=--character-set-server=hp8 --mysqld=--collation-server=hp8_english_ci',
    '--mysqld=--character-set-server=hp8 --mysqld=--collation-server=hp8_bin',
    '--mysqld=--character-set-server=hp8 --mysqld=--collation-server=hp8_english_nopad_ci',
    '--mysqld=--character-set-server=hp8 --mysqld=--collation-server=hp8_nopad_bin',
    '--mysqld=--character-set-server=koi8r --mysqld=--collation-server=koi8r_general_ci',
    '--mysqld=--character-set-server=koi8r --mysqld=--collation-server=koi8r_bin',
    '--mysqld=--character-set-server=koi8r --mysqld=--collation-server=koi8r_general_nopad_ci',
    '--mysqld=--character-set-server=koi8r --mysqld=--collation-server=koi8r_nopad_bin',
    '--mysqld=--character-set-server=latin1 --mysqld=--collation-server=latin1_german1_ci',
    '--mysqld=--character-set-server=latin1 --mysqld=--collation-server=latin1_swedish_ci',
    '--mysqld=--character-set-server=latin1 --mysqld=--collation-server=latin1_danish_ci',
    '--mysqld=--character-set-server=latin1 --mysqld=--collation-server=latin1_german2_ci',
    '--mysqld=--character-set-server=latin1 --mysqld=--collation-server=latin1_bin',
    '--mysqld=--character-set-server=latin1 --mysqld=--collation-server=latin1_general_ci',
    '--mysqld=--character-set-server=latin1 --mysqld=--collation-server=latin1_general_cs',
    '--mysqld=--character-set-server=latin1 --mysqld=--collation-server=latin1_spanish_ci',
    '--mysqld=--character-set-server=latin1 --mysqld=--collation-server=latin1_swedish_nopad_ci',
    '--mysqld=--character-set-server=latin1 --mysqld=--collation-server=latin1_nopad_bin',
    '--mysqld=--character-set-server=latin2 --mysqld=--collation-server=latin2_czech_cs',
    '--mysqld=--character-set-server=latin2 --mysqld=--collation-server=latin2_general_ci',
    '--mysqld=--character-set-server=latin2 --mysqld=--collation-server=latin2_hungarian_ci',
    '--mysqld=--character-set-server=latin2 --mysqld=--collation-server=latin2_croatian_ci',
    '--mysqld=--character-set-server=latin2 --mysqld=--collation-server=latin2_bin',
    '--mysqld=--character-set-server=latin2 --mysqld=--collation-server=latin2_general_nopad_ci',
    '--mysqld=--character-set-server=latin2 --mysqld=--collation-server=latin2_nopad_bin',
    '--mysqld=--character-set-server=ascii --mysqld=--collation-server=ascii_general_ci',
    '--mysqld=--character-set-server=ascii --mysqld=--collation-server=ascii_bin',
    '--mysqld=--character-set-server=ascii --mysqld=--collation-server=ascii_general_nopad_ci',
    '--mysqld=--character-set-server=ascii --mysqld=--collation-server=ascii_nopad_bin',
    '--mysqld=--character-set-server=ujis --mysqld=--collation-server=ujis_japanese_ci',
    '--mysqld=--character-set-server=ujis --mysqld=--collation-server=ujis_bin',
    '--mysqld=--character-set-server=ujis --mysqld=--collation-server=ujis_japanese_nopad_ci',
    '--mysqld=--character-set-server=ujis --mysqld=--collation-server=ujis_nopad_bin',
    '--mysqld=--character-set-server=sjis --mysqld=--collation-server=sjis_japanese_ci',
    '--mysqld=--character-set-server=sjis --mysqld=--collation-server=sjis_bin',
    '--mysqld=--character-set-server=sjis --mysqld=--collation-server=sjis_japanese_nopad_ci',
    '--mysqld=--character-set-server=sjis --mysqld=--collation-server=sjis_nopad_bin',
    '--mysqld=--character-set-server=hebrew --mysqld=--collation-server=hebrew_general_ci',
    '--mysqld=--character-set-server=hebrew --mysqld=--collation-server=hebrew_bin',
    '--mysqld=--character-set-server=hebrew --mysqld=--collation-server=hebrew_general_nopad_ci',
    '--mysqld=--character-set-server=hebrew --mysqld=--collation-server=hebrew_nopad_bin',
    '--mysqld=--character-set-server=tis620 --mysqld=--collation-server=tis620_thai_ci',
    '--mysqld=--character-set-server=tis620 --mysqld=--collation-server=tis620_bin',
    '--mysqld=--character-set-server=tis620 --mysqld=--collation-server=tis620_thai_nopad_ci',
    '--mysqld=--character-set-server=tis620 --mysqld=--collation-server=tis620_nopad_bin',
    '--mysqld=--character-set-server=euckr --mysqld=--collation-server=euckr_korean_ci',
    '--mysqld=--character-set-server=euckr --mysqld=--collation-server=euckr_bin',
    '--mysqld=--character-set-server=euckr --mysqld=--collation-server=euckr_korean_nopad_ci',
    '--mysqld=--character-set-server=euckr --mysqld=--collation-server=euckr_nopad_bin',
    '--mysqld=--character-set-server=koi8u --mysqld=--collation-server=koi8u_general_ci',
    '--mysqld=--character-set-server=koi8u --mysqld=--collation-server=koi8u_bin',
    '--mysqld=--character-set-server=koi8u --mysqld=--collation-server=koi8u_general_nopad_ci',
    '--mysqld=--character-set-server=koi8u --mysqld=--collation-server=koi8u_nopad_bin',
    '--mysqld=--character-set-server=gb2312 --mysqld=--collation-server=gb2312_chinese_ci',
    '--mysqld=--character-set-server=gb2312 --mysqld=--collation-server=gb2312_bin',
    '--mysqld=--character-set-server=gb2312 --mysqld=--collation-server=gb2312_chinese_nopad_ci',
    '--mysqld=--character-set-server=gb2312 --mysqld=--collation-server=gb2312_nopad_bin',
    '--mysqld=--character-set-server=greek --mysqld=--collation-server=greek_general_ci',
    '--mysqld=--character-set-server=greek --mysqld=--collation-server=greek_bin',
    '--mysqld=--character-set-server=greek --mysqld=--collation-server=greek_general_nopad_ci',
    '--mysqld=--character-set-server=greek --mysqld=--collation-server=greek_nopad_bin',
    '--mysqld=--character-set-server=cp1250 --mysqld=--collation-server=cp1250_general_ci',
    '--mysqld=--character-set-server=cp1250 --mysqld=--collation-server=cp1250_czech_cs',
    '--mysqld=--character-set-server=cp1250 --mysqld=--collation-server=cp1250_croatian_ci',
    '--mysqld=--character-set-server=cp1250 --mysqld=--collation-server=cp1250_bin',
    '--mysqld=--character-set-server=cp1250 --mysqld=--collation-server=cp1250_polish_ci',
    '--mysqld=--character-set-server=cp1250 --mysqld=--collation-server=cp1250_general_nopad_ci',
    '--mysqld=--character-set-server=cp1250 --mysqld=--collation-server=cp1250_nopad_bin',
    '--mysqld=--character-set-server=gbk --mysqld=--collation-server=gbk_chinese_ci',
    '--mysqld=--character-set-server=gbk --mysqld=--collation-server=gbk_bin',
    '--mysqld=--character-set-server=gbk --mysqld=--collation-server=gbk_chinese_nopad_ci',
    '--mysqld=--character-set-server=gbk --mysqld=--collation-server=gbk_nopad_bin',
    '--mysqld=--character-set-server=latin5 --mysqld=--collation-server=latin5_turkish_ci',
    '--mysqld=--character-set-server=latin5 --mysqld=--collation-server=latin5_bin',
    '--mysqld=--character-set-server=latin5 --mysqld=--collation-server=latin5_turkish_nopad_ci',
    '--mysqld=--character-set-server=latin5 --mysqld=--collation-server=latin5_nopad_bin',
    '--mysqld=--character-set-server=armscii8 --mysqld=--collation-server=armscii8_general_ci',
    '--mysqld=--character-set-server=armscii8 --mysqld=--collation-server=armscii8_bin',
    '--mysqld=--character-set-server=armscii8 --mysqld=--collation-server=armscii8_general_nopad_ci',
    '--mysqld=--character-set-server=armscii8 --mysqld=--collation-server=armscii8_nopad_bin',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_general_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_bin',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_unicode_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_icelandic_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_latvian_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_romanian_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_slovenian_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_polish_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_estonian_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_spanish_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_swedish_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_turkish_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_czech_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_danish_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_lithuanian_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_slovak_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_spanish2_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_roman_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_persian_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_esperanto_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_hungarian_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_sinhala_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_german2_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_croatian_mysql561_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_unicode_520_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_vietnamese_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_general_mysql500_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_croatian_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_myanmar_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_thai_520_w2',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_general_nopad_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_nopad_bin',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_unicode_nopad_ci',
    '--mysqld=--character-set-server=utf8 --mysqld=--collation-server=utf8_unicode_520_nopad_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_general_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_bin',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_unicode_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_icelandic_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_latvian_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_romanian_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_slovenian_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_polish_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_estonian_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_spanish_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_swedish_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_turkish_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_czech_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_danish_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_lithuanian_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_slovak_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_spanish2_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_roman_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_persian_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_esperanto_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_hungarian_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_sinhala_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_german2_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_croatian_mysql561_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_unicode_520_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_vietnamese_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_general_mysql500_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_croatian_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_myanmar_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_thai_520_w2',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_general_nopad_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_nopad_bin',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_unicode_nopad_ci',
    '--mysqld=--character-set-server=ucs2 --mysqld=--collation-server=ucs2_unicode_520_nopad_ci',
    '--mysqld=--character-set-server=cp866 --mysqld=--collation-server=cp866_general_ci',
    '--mysqld=--character-set-server=cp866 --mysqld=--collation-server=cp866_bin',
    '--mysqld=--character-set-server=cp866 --mysqld=--collation-server=cp866_general_nopad_ci',
    '--mysqld=--character-set-server=cp866 --mysqld=--collation-server=cp866_nopad_bin',
    '--mysqld=--character-set-server=keybcs2 --mysqld=--collation-server=keybcs2_general_ci',
    '--mysqld=--character-set-server=keybcs2 --mysqld=--collation-server=keybcs2_bin',
    '--mysqld=--character-set-server=keybcs2 --mysqld=--collation-server=keybcs2_general_nopad_ci',
    '--mysqld=--character-set-server=keybcs2 --mysqld=--collation-server=keybcs2_nopad_bin',
    '--mysqld=--character-set-server=macce --mysqld=--collation-server=macce_general_ci',
    '--mysqld=--character-set-server=macce --mysqld=--collation-server=macce_bin',
    '--mysqld=--character-set-server=macce --mysqld=--collation-server=macce_general_nopad_ci',
    '--mysqld=--character-set-server=macce --mysqld=--collation-server=macce_nopad_bin',
    '--mysqld=--character-set-server=macroman --mysqld=--collation-server=macroman_general_ci',
    '--mysqld=--character-set-server=macroman --mysqld=--collation-server=macroman_bin',
    '--mysqld=--character-set-server=macroman --mysqld=--collation-server=macroman_general_nopad_ci',
    '--mysqld=--character-set-server=macroman --mysqld=--collation-server=macroman_nopad_bin',
    '--mysqld=--character-set-server=cp852 --mysqld=--collation-server=cp852_general_ci',
    '--mysqld=--character-set-server=cp852 --mysqld=--collation-server=cp852_bin',
    '--mysqld=--character-set-server=cp852 --mysqld=--collation-server=cp852_general_nopad_ci',
    '--mysqld=--character-set-server=cp852 --mysqld=--collation-server=cp852_nopad_bin',
    '--mysqld=--character-set-server=latin7 --mysqld=--collation-server=latin7_estonian_cs',
    '--mysqld=--character-set-server=latin7 --mysqld=--collation-server=latin7_general_ci',
    '--mysqld=--character-set-server=latin7 --mysqld=--collation-server=latin7_general_cs',
    '--mysqld=--character-set-server=latin7 --mysqld=--collation-server=latin7_bin',
    '--mysqld=--character-set-server=latin7 --mysqld=--collation-server=latin7_general_nopad_ci',
    '--mysqld=--character-set-server=latin7 --mysqld=--collation-server=latin7_nopad_bin',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_general_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_bin',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_unicode_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_icelandic_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_latvian_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_romanian_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_slovenian_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_polish_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_estonian_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_spanish_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_swedish_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_turkish_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_czech_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_danish_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_lithuanian_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_slovak_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_spanish2_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_roman_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_persian_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_esperanto_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_hungarian_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_sinhala_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_german2_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_croatian_mysql561_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_unicode_520_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_vietnamese_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_croatian_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_myanmar_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_thai_520_w2',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_general_nopad_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_nopad_bin',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_unicode_nopad_ci',
    '--mysqld=--character-set-server=utf8mb4 --mysqld=--collation-server=utf8mb4_unicode_520_nopad_ci',
    '--mysqld=--character-set-server=cp1251 --mysqld=--collation-server=cp1251_bulgarian_ci',
    '--mysqld=--character-set-server=cp1251 --mysqld=--collation-server=cp1251_ukrainian_ci',
    '--mysqld=--character-set-server=cp1251 --mysqld=--collation-server=cp1251_bin',
    '--mysqld=--character-set-server=cp1251 --mysqld=--collation-server=cp1251_general_ci',
    '--mysqld=--character-set-server=cp1251 --mysqld=--collation-server=cp1251_general_cs',
    '--mysqld=--character-set-server=cp1251 --mysqld=--collation-server=cp1251_nopad_bin',
    '--mysqld=--character-set-server=cp1251 --mysqld=--collation-server=cp1251_general_nopad_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_general_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_bin',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_unicode_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_icelandic_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_latvian_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_romanian_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_slovenian_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_polish_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_estonian_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_spanish_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_swedish_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_turkish_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_czech_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_danish_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_lithuanian_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_slovak_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_spanish2_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_roman_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_persian_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_esperanto_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_hungarian_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_sinhala_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_german2_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_croatian_mysql561_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_unicode_520_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_vietnamese_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_croatian_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_myanmar_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_thai_520_w2',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_general_nopad_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_nopad_bin',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_unicode_nopad_ci',
    '--mysqld=--character-set-server=utf16 --mysqld=--collation-server=utf16_unicode_520_nopad_ci',
    '--mysqld=--character-set-server=utf16le --mysqld=--collation-server=utf16le_general_ci',
    '--mysqld=--character-set-server=utf16le --mysqld=--collation-server=utf16le_bin',
    '--mysqld=--character-set-server=utf16le --mysqld=--collation-server=utf16le_general_nopad_ci',
    '--mysqld=--character-set-server=utf16le --mysqld=--collation-server=utf16le_nopad_bin',
    '--mysqld=--character-set-server=cp1256 --mysqld=--collation-server=cp1256_general_ci',
    '--mysqld=--character-set-server=cp1256 --mysqld=--collation-server=cp1256_bin',
    '--mysqld=--character-set-server=cp1256 --mysqld=--collation-server=cp1256_general_nopad_ci',
    '--mysqld=--character-set-server=cp1256 --mysqld=--collation-server=cp1256_nopad_bin',
    '--mysqld=--character-set-server=cp1257 --mysqld=--collation-server=cp1257_lithuanian_ci',
    '--mysqld=--character-set-server=cp1257 --mysqld=--collation-server=cp1257_bin',
    '--mysqld=--character-set-server=cp1257 --mysqld=--collation-server=cp1257_general_ci',
    '--mysqld=--character-set-server=cp1257 --mysqld=--collation-server=cp1257_nopad_bin',
    '--mysqld=--character-set-server=cp1257 --mysqld=--collation-server=cp1257_general_nopad_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_general_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_bin',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_unicode_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_icelandic_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_latvian_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_romanian_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_slovenian_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_polish_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_estonian_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_spanish_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_swedish_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_turkish_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_czech_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_danish_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_lithuanian_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_slovak_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_spanish2_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_roman_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_persian_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_esperanto_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_hungarian_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_sinhala_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_german2_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_croatian_mysql561_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_unicode_520_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_vietnamese_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_croatian_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_myanmar_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_thai_520_w2',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_general_nopad_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_nopad_bin',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_unicode_nopad_ci',
    '--mysqld=--character-set-server=utf32 --mysqld=--collation-server=utf32_unicode_520_nopad_ci',
    '--mysqld=--character-set-server=binary --mysqld=--collation-server=binary',
    '--mysqld=--character-set-server=geostd8 --mysqld=--collation-server=geostd8_general_ci',
    '--mysqld=--character-set-server=geostd8 --mysqld=--collation-server=geostd8_bin',
    '--mysqld=--character-set-server=geostd8 --mysqld=--collation-server=geostd8_general_nopad_ci',
    '--mysqld=--character-set-server=geostd8 --mysqld=--collation-server=geostd8_nopad_bin',
    '--mysqld=--character-set-server=cp932 --mysqld=--collation-server=cp932_japanese_ci',
    '--mysqld=--character-set-server=cp932 --mysqld=--collation-server=cp932_bin',
    '--mysqld=--character-set-server=cp932 --mysqld=--collation-server=cp932_japanese_nopad_ci',
    '--mysqld=--character-set-server=cp932 --mysqld=--collation-server=cp932_nopad_bin',
    '--mysqld=--character-set-server=eucjpms --mysqld=--collation-server=eucjpms_japanese_ci',
    '--mysqld=--character-set-server=eucjpms --mysqld=--collation-server=eucjpms_bin',
    '--mysqld=--character-set-server=eucjpms --mysqld=--collation-server=eucjpms_japanese_nopad_ci',
    '--mysqld=--character-set-server=eucjpms --mysqld=--collation-server=eucjpms_nopad_bin',
  ],
];
